import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./build.css";

import { GeistSans } from 'geist/font/sans';
import Script from "next/script";
import { Providers } from "@/components/providers/providers";
// import { GeistMono } from 'geist/font/mono';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${GeistSans.className}  antialiased`}
      >
        <Providers attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </Providers>
        <Script
					defer
					src="https://cdn.tailwindcss.com"
				/>
        {/* <Script
					defer
					src="https://umami.alwurts.com/script.js"
					data-website-id="75179c08-085e-4342-a624-9acab944d858"
				/> */}
      </body>
    </html>
  );
}
