import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./build.css";
import { ToastProvider } from "@radix-ui/react-toast";

import { GeistSans } from 'geist/font/sans';
import Script from "next/script";
// import { GeistMono } from 'geist/font/mono';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${GeistSans.className}  antialiased`}
      >
        <ToastProvider>
          {children}
        </ToastProvider>
        <Script
					defer
					src="https://cdn.tailwindcss.com"
				/>
      </body>
    </html>
  );
}
